version: '3.8'

services:
  app:
    container_name: farmai_backend_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
      - .${STORAGE_HOST_PATH}:${STORAGE_CONTAINER_PATH}
    ports:
      - "8000:8000"
    networks:
      - farmai_network
    restart: always
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: '512M'
networks:
  farmai_network:
    driver: bridge

volumes:
  logs:
